"use client";
import {useMemo,useState} from "react";
type NodeItem={id:string;type:string;label:string;x:number;y:number;action?:string;payload?:any}; type EdgeItem={from:string;to:string};
const initialNodes:NodeItem[]=[{id:"trigger",type:"trigger",label:"Command Trigger",x:70,y:120},{id:"agent",type:"agent",label:"AI Agent",x:365,y:190},{id:"memory",type:"memory",label:"Company Brain",x:665,y:95},{id:"approval",type:"approval",label:"Human Review",x:665,y:330},{id:"tool",type:"tool",label:"Gmail Draft",x:960,y:210,action:"gmail_draft"}];
const initialEdges:EdgeItem[]=[{from:"trigger",to:"agent"},{from:"agent",to:"memory"},{from:"agent",to:"approval"},{from:"approval",to:"tool"}];
export default function DraggableWorkflowCanvas({companyId}:{companyId?:string|null}){const[nodes,setNodes]=useState(initialNodes); const[edges]=useState(initialEdges); const[drag,setDrag]=useState<{id:string;dx:number;dy:number}|null>(null); const[title,setTitle]=useState("AI Operations Workflow"); const[msg,setMsg]=useState(""); const nodeMap=useMemo(()=>{const m=new Map<string,NodeItem>(); nodes.forEach(n=>m.set(n.id,n)); return m},[nodes]);
function onMove(e:React.MouseEvent<HTMLDivElement>){if(!drag)return; const box=e.currentTarget.getBoundingClientRect(); const x=e.clientX-box.left-drag.dx; const y=e.clientY-box.top-drag.dy; setNodes(prev=>prev.map(n=>n.id===drag.id?{...n,x:Math.max(20,x),y:Math.max(20,y)}:n));}
async function save(){if(!companyId){setMsg("Create/login to a workspace before saving.");return;} setMsg("Saving workflow..."); const res=await fetch("/api/workflow-save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company_id:companyId,title,graph:{nodes,edges}})}); const json=await res.json(); setMsg(json.ok?"Workflow saved.":json.error||"Save failed.");}
async function run(){if(!companyId){setMsg("Create/login to a workspace before running.");return;} setMsg("Running workflow..."); const res=await fetch("/api/workflow-execute",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company_id:companyId,graph:{nodes,edges},input:{source:"canvas"}})}); const json=await res.json(); setMsg(json.ok?"Workflow run completed/queued.":json.error||"Run failed.");}
return <div><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} className="w-[320px] rounded-lg border border-neutral-200 bg-white px-3 py-2 text-sm font-bold"/><div className="flex gap-2"><button onClick={save} className="rounded-lg border border-neutral-200 bg-white px-4 py-2 text-sm font-bold">Save Graph</button><button onClick={run} className="rounded-lg bg-black px-4 py-2 text-sm font-bold text-white">Run Workflow</button></div></div>{msg&&<p className="mb-3 rounded-xl bg-neutral-100 p-3 text-sm font-bold text-neutral-700">{msg}</p>}<div className="relative h-[720px] overflow-hidden rounded-2xl border border-neutral-200 bg-white" onMouseMove={onMove} onMouseUp={()=>setDrag(null)} onMouseLeave={()=>setDrag(null)}><div className="absolute inset-0 bg-[linear-gradient(#eee_1px,transparent_1px),linear-gradient(90deg,#eee_1px,transparent_1px)] bg-[size:28px_28px]"/><svg className="absolute inset-0 h-full w-full">{edges.map(edge=>{const a=nodeMap.get(edge.from); const b=nodeMap.get(edge.to); if(!a||!b)return null; const ax=a.x+190; const ay=a.y+50; const bx=b.x; const by=b.y+50; return <path key={`${edge.from}-${edge.to}`} d={`M${ax} ${ay} C${ax+80} ${ay} ${bx-80} ${by} ${bx} ${by}`} fill="none" stroke="#111" strokeWidth="2"/>})}</svg>{nodes.map(node=><div key={node.id} className="absolute w-[190px] cursor-grab rounded-xl border border-neutral-300 bg-white p-4 shadow-lg active:cursor-grabbing" style={{left:node.x,top:node.y}} onMouseDown={e=>{const rect=e.currentTarget.getBoundingClientRect(); setDrag({id:node.id,dx:e.clientX-rect.left,dy:e.clientY-rect.top})}}><p className="text-[11px] font-black uppercase tracking-[.14em] text-neutral-400">{node.type}</p><h3 className="mt-2 font-black">{node.label}</h3><p className="mt-2 text-xs text-neutral-500">Drag to move</p></div>)}</div></div>}
